# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 528)
        MainWindow.setMinimumSize(QtCore.QSize(729, 528))
        MainWindow.setMaximumSize(QtCore.QSize(729, 528))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 711, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidgetAssortment = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetAssortment.setGeometry(QtCore.QRect(0, 110, 709, 321))
        self.tableWidgetAssortment.setObjectName("tableWidgetAssortment")
        self.tableWidgetAssortment.setColumnCount(0)
        self.tableWidgetAssortment.setRowCount(0)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 709, 98))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nameSAssortment = QtWidgets.QLineEdit(self.layoutWidget1)
        self.nameSAssortment.setObjectName("nameSAssortment")
        self.verticalLayout.addWidget(self.nameSAssortment)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchButtonAssortment = QtWidgets.QPushButton(self.layoutWidget1)
        self.searchButtonAssortment.setObjectName("searchButtonAssortment")
        self.horizontalLayout.addWidget(self.searchButtonAssortment)
        self.deleteButtonAssortment = QtWidgets.QPushButton(self.layoutWidget1)
        self.deleteButtonAssortment.setObjectName("deleteButtonAssortment")
        self.horizontalLayout.addWidget(self.deleteButtonAssortment)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nameAssortment = QtWidgets.QLineEdit(self.layoutWidget1)
        self.nameAssortment.setObjectName("nameAssortment")
        self.horizontalLayout_3.addWidget(self.nameAssortment)
        self.stockAssortment = QtWidgets.QLineEdit(self.layoutWidget1)
        self.stockAssortment.setObjectName("stockAssortment")
        self.horizontalLayout_3.addWidget(self.stockAssortment)
        self.priceAssortment = QtWidgets.QLineEdit(self.layoutWidget1)
        self.priceAssortment.setObjectName("priceAssortment")
        self.horizontalLayout_3.addWidget(self.priceAssortment)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.addButtonAssortment = QtWidgets.QPushButton(self.layoutWidget1)
        self.addButtonAssortment.setObjectName("addButtonAssortment")
        self.verticalLayout_4.addWidget(self.addButtonAssortment)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidgetOrders = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetOrders.setGeometry(QtCore.QRect(0, 110, 709, 321))
        self.tableWidgetOrders.setObjectName("tableWidgetOrders")
        self.tableWidgetOrders.setColumnCount(0)
        self.tableWidgetOrders.setRowCount(0)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 709, 98))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deleteButtonOrders = QtWidgets.QPushButton(self.layoutWidget_2)
        self.deleteButtonOrders.setObjectName("deleteButtonOrders")
        self.horizontalLayout_6.addWidget(self.deleteButtonOrders)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ItemOrders = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ItemOrders.setObjectName("ItemOrders")
        self.horizontalLayout_8.addWidget(self.ItemOrders)
        self.QuantityOrders = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.QuantityOrders.setObjectName("QuantityOrders")
        self.horizontalLayout_8.addWidget(self.QuantityOrders)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.addButtonOrders = QtWidgets.QPushButton(self.layoutWidget_2)
        self.addButtonOrders.setObjectName("addButtonOrders")
        self.verticalLayout_7.addWidget(self.addButtonOrders)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        self.menuRecord = QtWidgets.QMenu(self.menubar)
        self.menuRecord.setObjectName("menuRecord")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setEnabled(True)
        self.actionConnect.setObjectName("actionConnect")
        self.actionClear_all_tables = QtWidgets.QAction(MainWindow)
        self.actionClear_all_tables.setObjectName("actionClear_all_tables")
        self.actionClear_table = QtWidgets.QAction(MainWindow)
        self.actionClear_table.setObjectName("actionClear_table")
        self.actionDrop_database = QtWidgets.QAction(MainWindow)
        self.actionDrop_database.setObjectName("actionDrop_database")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionDrop_database)
        self.menuTable.addAction(self.actionClear_table)
        self.menuTable.addAction(self.actionClear_all_tables)
        self.menuRecord.addAction(self.actionDelete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())
        self.menubar.addAction(self.menuRecord.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weed Store DB"))
        self.label.setText(_translate("MainWindow", "Enter name:"))
        self.searchButtonAssortment.setText(_translate("MainWindow", "Search"))
        self.deleteButtonAssortment.setText(_translate("MainWindow", "Delete"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "Stock"))
        self.label_5.setText(_translate("MainWindow", "Price"))
        self.addButtonAssortment.setText(_translate("MainWindow", "Add record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Assortment"))
        self.deleteButtonOrders.setText(_translate("MainWindow", "Delete"))
        self.label_7.setText(_translate("MainWindow", "Item"))
        self.label_8.setText(_translate("MainWindow", "Quantity"))
        self.addButtonOrders.setText(_translate("MainWindow", "Add record"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Orders"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.menuRecord.setTitle(_translate("MainWindow", "Record"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClear_all_tables.setText(_translate("MainWindow", "Clear all tables"))
        self.actionClear_all_tables.setShortcut(_translate("MainWindow", "Ctrl+Shift+Backspace"))
        self.actionClear_table.setText(_translate("MainWindow", "Clear table"))
        self.actionClear_table.setShortcut(_translate("MainWindow", "Ctrl+Backspace"))
        self.actionDrop_database.setText(_translate("MainWindow", "Drop database"))
        self.actionDrop_database.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Backspace"))
